name: Test Build Packages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - dev-python/uproot
          - dev-python/awkward
          - dev-libs/arrow
          - dev-python/pyarrow[python]
    container:
      image: gentoo/stage3:systemd
    steps:
      - uses: actions/checkout@v2
      - name: Sync portage repository
        run: emerge --sync
      - name: Add overlay
        run: |
          echo ACCEPT_KEYWORDS=\"~amd64\" >> /etc/portage/make.conf
          emerge app-eselect/eselect-repository
          touch /etc/portage/repos.conf
          eselect repository create overlay ${GITHUB_WORKSPACE}
      - name: Emerge ${{ matrix.package }}
        run: |
          if [[ ${matrix.package} =~ ([a-zA-Z0-9\-]+/[a-zA-Z0-9\-]+)(\[([a-zA-Z0-9\,\-]+)\])? ]]; then
            USE=${BASH_REMATCH[3]} emerge ${BASH_REMATCH[1]}
          else
            emerge ${{ matrix.package }}
          fi
